// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phone.proto

package com.basic.hbase.model;

public final class Phone {
  private Phone() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface phonedetailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.basic.hbase.phonedetail)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string pnumber = 1;</code>
     */
    boolean hasPnumber();
    /**
     * <code>required string pnumber = 1;</code>
     */
    String getPnumber();
    /**
     * <code>required string pnumber = 1;</code>
     */
    com.google.protobuf.ByteString
        getPnumberBytes();

    /**
     * <code>required string type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 2;</code>
     */
    String getType();
    /**
     * <code>required string type = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>required string time = 3;</code>
     */
    boolean hasTime();
    /**
     * <code>required string time = 3;</code>
     */
    String getTime();
    /**
     * <code>required string time = 3;</code>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <code>required string duration = 4;</code>
     */
    boolean hasDuration();
    /**
     * <code>required string duration = 4;</code>
     */
    String getDuration();
    /**
     * <code>required string duration = 4;</code>
     */
    com.google.protobuf.ByteString
        getDurationBytes();
  }
  /**
   * Protobuf type {@code com.basic.hbase.phonedetail}
   */
  public static final class phonedetail extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.basic.hbase.phonedetail)
      phonedetailOrBuilder {
    // Use phonedetail.newBuilder() to construct.
    private phonedetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private phonedetail(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final phonedetail defaultInstance;
    public static phonedetail getDefaultInstance() {
      return defaultInstance;
    }

    public phonedetail getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private phonedetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              pnumber_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              type_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              time_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              duration_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Phone.internal_static_com_basic_hbase_phonedetail_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Phone.internal_static_com_basic_hbase_phonedetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              phonedetail.class, Builder.class);
    }

    public static com.google.protobuf.Parser<phonedetail> PARSER =
        new com.google.protobuf.AbstractParser<phonedetail>() {
      public phonedetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new phonedetail(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<phonedetail> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PNUMBER_FIELD_NUMBER = 1;
    private Object pnumber_;
    /**
     * <code>required string pnumber = 1;</code>
     */
    public boolean hasPnumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string pnumber = 1;</code>
     */
    public String getPnumber() {
      Object ref = pnumber_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pnumber_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string pnumber = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPnumberBytes() {
      Object ref = pnumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pnumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private Object type_;
    /**
     * <code>required string type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string type = 2;</code>
     */
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private Object time_;
    /**
     * <code>required string time = 3;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string time = 3;</code>
     */
    public String getTime() {
      Object ref = time_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          time_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string time = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DURATION_FIELD_NUMBER = 4;
    private Object duration_;
    /**
     * <code>required string duration = 4;</code>
     */
    public boolean hasDuration() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string duration = 4;</code>
     */
    public String getDuration() {
      Object ref = duration_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          duration_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string duration = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDurationBytes() {
      Object ref = duration_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        duration_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      pnumber_ = "";
      type_ = "";
      time_ = "";
      duration_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPnumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDuration()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPnumberBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDurationBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPnumberBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDurationBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static phonedetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static phonedetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static phonedetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static phonedetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static phonedetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static phonedetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static phonedetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static phonedetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static phonedetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static phonedetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(phonedetail prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.basic.hbase.phonedetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.basic.hbase.phonedetail)
        phonedetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Phone.internal_static_com_basic_hbase_phonedetail_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Phone.internal_static_com_basic_hbase_phonedetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                phonedetail.class, Builder.class);
      }

      // Construct using com.basic.hbase.model.Phone.phonedetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        pnumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        duration_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Phone.internal_static_com_basic_hbase_phonedetail_descriptor;
      }

      public phonedetail getDefaultInstanceForType() {
        return phonedetail.getDefaultInstance();
      }

      public phonedetail build() {
        phonedetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public phonedetail buildPartial() {
        phonedetail result = new phonedetail(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pnumber_ = pnumber_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.duration_ = duration_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof phonedetail) {
          return mergeFrom((phonedetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(phonedetail other) {
        if (other == phonedetail.getDefaultInstance()) return this;
        if (other.hasPnumber()) {
          bitField0_ |= 0x00000001;
          pnumber_ = other.pnumber_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000002;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasTime()) {
          bitField0_ |= 0x00000004;
          time_ = other.time_;
          onChanged();
        }
        if (other.hasDuration()) {
          bitField0_ |= 0x00000008;
          duration_ = other.duration_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPnumber()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        if (!hasDuration()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        phonedetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (phonedetail) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object pnumber_ = "";
      /**
       * <code>required string pnumber = 1;</code>
       */
      public boolean hasPnumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string pnumber = 1;</code>
       */
      public String getPnumber() {
        Object ref = pnumber_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pnumber_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string pnumber = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPnumberBytes() {
        Object ref = pnumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pnumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string pnumber = 1;</code>
       */
      public Builder setPnumber(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pnumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string pnumber = 1;</code>
       */
      public Builder clearPnumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pnumber_ = getDefaultInstance().getPnumber();
        onChanged();
        return this;
      }
      /**
       * <code>required string pnumber = 1;</code>
       */
      public Builder setPnumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pnumber_ = value;
        onChanged();
        return this;
      }

      private Object type_ = "";
      /**
       * <code>required string type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string type = 2;</code>
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder setType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }

      private Object time_ = "";
      /**
       * <code>required string time = 3;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string time = 3;</code>
       */
      public String getTime() {
        Object ref = time_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            time_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string time = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string time = 3;</code>
       */
      public Builder setTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 3;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 3;</code>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        time_ = value;
        onChanged();
        return this;
      }

      private Object duration_ = "";
      /**
       * <code>required string duration = 4;</code>
       */
      public boolean hasDuration() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string duration = 4;</code>
       */
      public String getDuration() {
        Object ref = duration_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            duration_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string duration = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDurationBytes() {
        Object ref = duration_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          duration_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string duration = 4;</code>
       */
      public Builder setDuration(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        duration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string duration = 4;</code>
       */
      public Builder clearDuration() {
        bitField0_ = (bitField0_ & ~0x00000008);
        duration_ = getDefaultInstance().getDuration();
        onChanged();
        return this;
      }
      /**
       * <code>required string duration = 4;</code>
       */
      public Builder setDurationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        duration_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.basic.hbase.phonedetail)
    }

    static {
      defaultInstance = new phonedetail(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.basic.hbase.phonedetail)
  }

  public interface phonedayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.basic.hbase.phoneday)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
     */
    java.util.List<phonedetail>
        getPhonelistList();
    /**
     * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
     */
    phonedetail getPhonelist(int index);
    /**
     * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
     */
    int getPhonelistCount();
    /**
     * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
     */
    java.util.List<? extends phonedetailOrBuilder>
        getPhonelistOrBuilderList();
    /**
     * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
     */
    phonedetailOrBuilder getPhonelistOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code com.basic.hbase.phoneday}
   */
  public static final class phoneday extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.basic.hbase.phoneday)
      phonedayOrBuilder {
    // Use phoneday.newBuilder() to construct.
    private phoneday(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private phoneday(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final phoneday defaultInstance;
    public static phoneday getDefaultInstance() {
      return defaultInstance;
    }

    public phoneday getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private phoneday(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                phonelist_ = new java.util.ArrayList<phonedetail>();
                mutable_bitField0_ |= 0x00000001;
              }
              phonelist_.add(input.readMessage(phonedetail.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          phonelist_ = java.util.Collections.unmodifiableList(phonelist_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Phone.internal_static_com_basic_hbase_phoneday_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Phone.internal_static_com_basic_hbase_phoneday_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              phoneday.class, Builder.class);
    }

    public static com.google.protobuf.Parser<phoneday> PARSER =
        new com.google.protobuf.AbstractParser<phoneday>() {
      public phoneday parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new phoneday(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<phoneday> getParserForType() {
      return PARSER;
    }

    public static final int PHONELIST_FIELD_NUMBER = 1;
    private java.util.List<phonedetail> phonelist_;
    /**
     * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
     */
    public java.util.List<phonedetail> getPhonelistList() {
      return phonelist_;
    }
    /**
     * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
     */
    public java.util.List<? extends phonedetailOrBuilder>
        getPhonelistOrBuilderList() {
      return phonelist_;
    }
    /**
     * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
     */
    public int getPhonelistCount() {
      return phonelist_.size();
    }
    /**
     * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
     */
    public phonedetail getPhonelist(int index) {
      return phonelist_.get(index);
    }
    /**
     * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
     */
    public phonedetailOrBuilder getPhonelistOrBuilder(
        int index) {
      return phonelist_.get(index);
    }

    private void initFields() {
      phonelist_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getPhonelistCount(); i++) {
        if (!getPhonelist(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < phonelist_.size(); i++) {
        output.writeMessage(1, phonelist_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < phonelist_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, phonelist_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static phoneday parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static phoneday parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static phoneday parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static phoneday parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static phoneday parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static phoneday parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static phoneday parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static phoneday parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static phoneday parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static phoneday parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(phoneday prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.basic.hbase.phoneday}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.basic.hbase.phoneday)
        phonedayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Phone.internal_static_com_basic_hbase_phoneday_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Phone.internal_static_com_basic_hbase_phoneday_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                phoneday.class, Builder.class);
      }

      // Construct using com.basic.hbase.model.Phone.phoneday.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPhonelistFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (phonelistBuilder_ == null) {
          phonelist_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          phonelistBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Phone.internal_static_com_basic_hbase_phoneday_descriptor;
      }

      public phoneday getDefaultInstanceForType() {
        return phoneday.getDefaultInstance();
      }

      public phoneday build() {
        phoneday result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public phoneday buildPartial() {
        phoneday result = new phoneday(this);
        int from_bitField0_ = bitField0_;
        if (phonelistBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            phonelist_ = java.util.Collections.unmodifiableList(phonelist_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.phonelist_ = phonelist_;
        } else {
          result.phonelist_ = phonelistBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof phoneday) {
          return mergeFrom((phoneday)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(phoneday other) {
        if (other == phoneday.getDefaultInstance()) return this;
        if (phonelistBuilder_ == null) {
          if (!other.phonelist_.isEmpty()) {
            if (phonelist_.isEmpty()) {
              phonelist_ = other.phonelist_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePhonelistIsMutable();
              phonelist_.addAll(other.phonelist_);
            }
            onChanged();
          }
        } else {
          if (!other.phonelist_.isEmpty()) {
            if (phonelistBuilder_.isEmpty()) {
              phonelistBuilder_.dispose();
              phonelistBuilder_ = null;
              phonelist_ = other.phonelist_;
              bitField0_ = (bitField0_ & ~0x00000001);
              phonelistBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPhonelistFieldBuilder() : null;
            } else {
              phonelistBuilder_.addAllMessages(other.phonelist_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPhonelistCount(); i++) {
          if (!getPhonelist(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        phoneday parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (phoneday) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<phonedetail> phonelist_ =
        java.util.Collections.emptyList();
      private void ensurePhonelistIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          phonelist_ = new java.util.ArrayList<phonedetail>(phonelist_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          phonedetail, phonedetail.Builder, phonedetailOrBuilder> phonelistBuilder_;

      /**
       * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
       */
      public java.util.List<phonedetail> getPhonelistList() {
        if (phonelistBuilder_ == null) {
          return java.util.Collections.unmodifiableList(phonelist_);
        } else {
          return phonelistBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
       */
      public int getPhonelistCount() {
        if (phonelistBuilder_ == null) {
          return phonelist_.size();
        } else {
          return phonelistBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
       */
      public phonedetail getPhonelist(int index) {
        if (phonelistBuilder_ == null) {
          return phonelist_.get(index);
        } else {
          return phonelistBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
       */
      public Builder setPhonelist(
          int index, phonedetail value) {
        if (phonelistBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhonelistIsMutable();
          phonelist_.set(index, value);
          onChanged();
        } else {
          phonelistBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
       */
      public Builder setPhonelist(
          int index, phonedetail.Builder builderForValue) {
        if (phonelistBuilder_ == null) {
          ensurePhonelistIsMutable();
          phonelist_.set(index, builderForValue.build());
          onChanged();
        } else {
          phonelistBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
       */
      public Builder addPhonelist(phonedetail value) {
        if (phonelistBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhonelistIsMutable();
          phonelist_.add(value);
          onChanged();
        } else {
          phonelistBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
       */
      public Builder addPhonelist(
          int index, phonedetail value) {
        if (phonelistBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhonelistIsMutable();
          phonelist_.add(index, value);
          onChanged();
        } else {
          phonelistBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
       */
      public Builder addPhonelist(
          phonedetail.Builder builderForValue) {
        if (phonelistBuilder_ == null) {
          ensurePhonelistIsMutable();
          phonelist_.add(builderForValue.build());
          onChanged();
        } else {
          phonelistBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
       */
      public Builder addPhonelist(
          int index, phonedetail.Builder builderForValue) {
        if (phonelistBuilder_ == null) {
          ensurePhonelistIsMutable();
          phonelist_.add(index, builderForValue.build());
          onChanged();
        } else {
          phonelistBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
       */
      public Builder addAllPhonelist(
          Iterable<? extends phonedetail> values) {
        if (phonelistBuilder_ == null) {
          ensurePhonelistIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, phonelist_);
          onChanged();
        } else {
          phonelistBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
       */
      public Builder clearPhonelist() {
        if (phonelistBuilder_ == null) {
          phonelist_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          phonelistBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
       */
      public Builder removePhonelist(int index) {
        if (phonelistBuilder_ == null) {
          ensurePhonelistIsMutable();
          phonelist_.remove(index);
          onChanged();
        } else {
          phonelistBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
       */
      public phonedetail.Builder getPhonelistBuilder(
          int index) {
        return getPhonelistFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
       */
      public phonedetailOrBuilder getPhonelistOrBuilder(
          int index) {
        if (phonelistBuilder_ == null) {
          return phonelist_.get(index);  } else {
          return phonelistBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
       */
      public java.util.List<? extends phonedetailOrBuilder>
           getPhonelistOrBuilderList() {
        if (phonelistBuilder_ != null) {
          return phonelistBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(phonelist_);
        }
      }
      /**
       * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
       */
      public phonedetail.Builder addPhonelistBuilder() {
        return getPhonelistFieldBuilder().addBuilder(
            phonedetail.getDefaultInstance());
      }
      /**
       * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
       */
      public phonedetail.Builder addPhonelistBuilder(
          int index) {
        return getPhonelistFieldBuilder().addBuilder(
            index, phonedetail.getDefaultInstance());
      }
      /**
       * <code>repeated .com.basic.hbase.phonedetail phonelist = 1;</code>
       */
      public java.util.List<phonedetail.Builder>
           getPhonelistBuilderList() {
        return getPhonelistFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          phonedetail, phonedetail.Builder, phonedetailOrBuilder>
          getPhonelistFieldBuilder() {
        if (phonelistBuilder_ == null) {
          phonelistBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              phonedetail, phonedetail.Builder, phonedetailOrBuilder>(
                  phonelist_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          phonelist_ = null;
        }
        return phonelistBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.basic.hbase.phoneday)
    }

    static {
      defaultInstance = new phoneday(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.basic.hbase.phoneday)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_basic_hbase_phonedetail_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_basic_hbase_phonedetail_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_basic_hbase_phoneday_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_basic_hbase_phoneday_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013phone.proto\022\017com.basic.hbase\"L\n\013phoned" +
      "etail\022\017\n\007pnumber\030\001 \002(\t\022\014\n\004type\030\002 \002(\t\022\014\n\004" +
      "time\030\003 \002(\t\022\020\n\010duration\030\004 \002(\t\";\n\010phoneday" +
      "\022/\n\tphonelist\030\001 \003(\0132\034.com.basic.hbase.ph" +
      "onedetail"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_basic_hbase_phonedetail_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_basic_hbase_phonedetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_basic_hbase_phonedetail_descriptor,
        new String[] { "Pnumber", "Type", "Time", "Duration", });
    internal_static_com_basic_hbase_phoneday_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_basic_hbase_phoneday_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_basic_hbase_phoneday_descriptor,
        new String[] { "Phonelist", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
